# Uncomment the next line to define a global platform for your project
 platform :ios, '12.4'

target 'TheTasteV0.0.1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheTasteV0.0.1
  
pod 'GoogleAnalytics'
pod 'Firebase'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

end
